import {t} from '@/locale/server';

import type {ShopProductDetailLabels} from '@/subapps/shop/common/ui/components';

export async function buildProductDetailLabels(): Promise<ShopProductDetailLabels> {
  const [
    categoriesTitle,
    allProducts,
    breadcrumbRoot,
    refLabel,
    inStockBadge,
    inStockRemainingPrefix,
    outOfStockBadge,
    htSuffix,
    ttcSuffix,
    quantityLabel,
    addToCart,
    reassuranceDelivery,
    reassuranceWarranty,
    reassuranceInvoice,
    tabDescription,
    tabSpecs,
    specRef,
    specCategory,
    specWarranty,
    specDelivery,
    warrantyValue,
    deliveryInStock,
    deliveryOnOrder,
    relatedTitle,
  ] = await Promise.all([
    t('Categories'),
    t('All products'),
    t('Catalogue'),
    t('Ref.'),
    t('In stock'),
    t('In stock · {0} remaining'),
    t('Out of stock'),
    t('excl. tax'),
    t('incl. tax'),
    t('Quantity'),
    t('Add to cart'),
    t('Tracked delivery'),
    t('2-year warranty'),
    t('Business invoice'),
    t('Description'),
    t('Specifications'),
    t('Reference'),
    t('Category'),
    t('Warranty'),
    t('Lead time'),
    t('2 years parts & labour'),
    t('5–10 business days'),
    t('On order (4–6 weeks)'),
    t('In the same category'),
  ]);

  return {
    categoriesTitle,
    allProducts,
    breadcrumbRoot,
    refLabel,
    inStockBadge,
    inStockRemainingPrefix,
    outOfStockBadge,
    htSuffix,
    ttcSuffix,
    quantityLabel,
    addToCart,
    reassuranceDelivery,
    reassuranceWarranty,
    reassuranceInvoice,
    tabDescription,
    tabSpecs,
    specRef,
    specCategory,
    specWarranty,
    specDelivery,
    warrantyValue,
    deliveryInStock,
    deliveryOnOrder,
    relatedTitle,
  };
}
